liste=[1,10,34,60,54]
liste2=["Ali","Veli","Lale","Jale"]
liste.sort()
print(liste)
liste2.reverse()
print(liste2)
liste.append(liste2)
print(liste)
print(liste[4])
print(liste[5])
print(liste[5][2][3])
